import Footer from "@/components/site/Footer";
import Header from "@/components/site/Header";
export const metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function mainlayout({ children }) {
  return (
    <div className="min-h-full flex flex-col">
      <Header/>
        {children}
        <Footer/>
    </div>
    
  );
}
